theme: jekyll-theme-hacker
markdown: rouge
encoding: UTF-8                
highlighter: pygments          # rouge now causes Page Build Failure on GitHub
paginate: 10                   # blog posts per page
safe: true
lsi: false