theme: jekyll-theme-hacker
markdown: kramdown
encoding: UTF-8                
highlighter: rouge
paginate: 10
safe: true
lsi: false
permalink: date
paginate_path: /page:num
collections:
  posts:
    output:   true